### ISSUE TITLE
/dev/mapper empty

### ISSUE THREAD

**Issue by marc-git** [jeffmahoney/sparsebundle-loopback#2]
Hello there, thanks for writing this. After doing the step with `kpartx -a /dev/loop#`, the next step `mount -r -t hfsplus /dev/mapper/loop#p2 /mnt2` doesn't work because only `loop-control` is present in `/dev/mapper` 
I am running debian sid.  Any ideas what is wrong there?

**Comment by jeffmahoney** [comment]
Forgive the obvious question, but are you using literally `/dev/loop#` or have you substituted the real device name?

**Comment by marc-git** [comment]
Hi there, thanks for being diplomatic! Yes I chose one of the numbers available. But i think my problem has more to do with a  corrupted sparsebundle. I'll close this issue and get back to you.
